/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Base: typeof import('./components/wizards/Config/Headers/Base.vue')['default']
    Config: typeof import('./components/wizards/Config/index.vue')['default']
    Head: typeof import('./components/wizards/Config/Welcome/head.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InitialConfig: typeof import('./components/wizards/Config/initialConfig.vue')['default']
    Item: typeof import('./components/wizards/Config/Base/item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Start: typeof import('./components/wizards/Config/Start.vue')['default']
    Step: typeof import('./components/wizards/Config/Step.vue')['default']
  }
}
